/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package akhirpbo;


import java.text.SimpleDateFormat;
import java.util.Date;

public class Mahasiswaform extends javax.swing.JFrame {
    
    private final MahasiswaDAO mahasiswaDAO; // Deklarasi objek MahasiswaDAO
    
    
    public Mahasiswaform() {
        initComponents();
        setVisible(true);
        this.mahasiswaDAO = new MahasiswaDAO(); // Inisialisasi objek MahasiswaDAO
        
    }
    
    
    // Method untuk membersihkan semua input field
    private void bersihkanInput() {
        jTextnama.setText("");
        jTextnim.setText("");
        jTextjurusan.setText("");
        
        jDatetanggals.setDate(null); // Mengosongkan tanggal
        jTextno.setText("");
        
    }

    // Method untuk menyimpan data ke database menggunakan MahasiswaDAO
    private void simpanData() {
        String nama = jTextnama.getText();
        String nim = jTextnim.getText();
        String jurusan = jTextjurusan.getText();
        // Mengambil tanggal dari JDateChooser
        Date tanggalLahir = jDatetanggals.getDate();
        // Mengubah tanggal ke dalam format yang sesuai dengan database (misalnya, tanggal dalam format yyyy-MM-dd)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalLahirStr = sdf.format(tanggalLahir);
        String nomorTelepon = jTextno.getText();

        // Memanggil method simpanMahasiswa() dari objek mahasiswaDAO
        mahasiswaDAO.simpanMahasiswa(nama, nim, jurusan, tanggalLahirStr, nomorTelepon);
    }

    // Method untuk menampilkan data
    private void lihatData() {
        // Panggil method lihatMahasiswa() dari objek mahasiswaDAO
        String data = mahasiswaDAO.lihatMahasiswa();
        // Set teks area dengan data mahasiswa
        jTextArea1.setText(data);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextnama = new javax.swing.JTextField();
        jTextnim = new javax.swing.JTextField();
        jTextjurusan = new javax.swing.JTextField();
        jTextno = new javax.swing.JTextField();
        jButtonlihat = new javax.swing.JButton();
        jButtonsimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButtonlihat2 = new javax.swing.JButton();
        jDatetanggals = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama:");

        jLabel2.setText("Nim:");

        jLabel3.setText("Jurusan:");

        jLabel4.setText("Tanggal Lahir:");

        jLabel5.setText("Nomor HP:");

        jTextnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnamaActionPerformed(evt);
            }
        });

        jTextnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnimActionPerformed(evt);
            }
        });

        jTextjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextjurusanActionPerformed(evt);
            }
        });

        jTextno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnoActionPerformed(evt);
            }
        });

        jButtonlihat.setText("Lihat");
        jButtonlihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlihatActionPerformed(evt);
            }
        });

        jButtonsimpan.setText("Simpan");
        jButtonsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsimpanActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("Daftar  Nama Mahasiswa");

        jButtonlihat2.setText("Back");
        jButtonlihat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlihat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jButtonlihat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonlihat2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextno)
                            .addComponent(jDatetanggals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextjurusan)
                            .addComponent(jTextnim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextnama))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDatetanggals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonlihat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonlihat2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextjurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextjurusanActionPerformed

    private void jButtonsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsimpanActionPerformed
        simpanData();
        bersihkanInput();
    }//GEN-LAST:event_jButtonsimpanActionPerformed

    private void jButtonlihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlihatActionPerformed
        lihatData();
    }//GEN-LAST:event_jButtonlihatActionPerformed

    private void jTextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnamaActionPerformed

    private void jTextnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnimActionPerformed

    private void jTextnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnoActionPerformed

    private void jButtonlihat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlihat2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonlihat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonlihat;
    private javax.swing.JButton jButtonlihat2;
    private javax.swing.JButton jButtonsimpan;
    private com.toedter.calendar.JDateChooser jDatetanggals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextjurusan;
    private javax.swing.JTextField jTextnama;
    private javax.swing.JTextField jTextnim;
    private javax.swing.JTextField jTextno;
    // End of variables declaration//GEN-END:variables
}
