/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package akhirpbo;

/**
 *
 * @author ASUS
 */
public class NilaiForm extends javax.swing.JFrame {

    private final MahasiswaDAO mahasiswaDAO;
  
    public NilaiForm() {
        initComponents();
        this.mahasiswaDAO = new MahasiswaDAO();
        setVisible(true);
    }

    
    // Method untuk membersihkan semua input field
    private void bersihkanInput() {
        jTexttugas.setText("");
        jTextkuis.setText("");
        jTextmid.setText("");
        jTextsemester.setText("");
        jTextrata.setText("");
        jTexthuruf.setText("");
    }
    // Method untuk melakukan perhitungan nilai
    private void hitungNilai() {
        try {
            double tugas = Double.parseDouble(jTexttugas.getText());
            double kuis = Double.parseDouble(jTextkuis.getText());
            double mid = Double.parseDouble(jTextmid.getText());
            double semester = Double.parseDouble(jTextsemester.getText());

            double rata = (tugas + kuis + mid + semester) / 4;
            jTextrata.setText(String.valueOf(rata));

            // Menghitung nilai huruf berdasarkan rata-rata
            String huruf;
            if (rata >= 85) {
                huruf = "A";
            } else if (rata >= 75) {
                huruf = "B";
            } else if (rata >= 65) {
                huruf = "C";
            } else {
                huruf = "D";
            }
            jTexthuruf.setText(huruf);
        } catch (NumberFormatException e) {
            
        }
    }

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {
        hitungNilai();
    }

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        String nim = jTextnim.getText();  
        String tugas = jTexttugas.getText();
        String kuis = jTextkuis.getText();
        String mid = jTextmid.getText();
        String semester = jTextsemester.getText();
        String rata = jTextrata.getText();
        String huruf = jTexthuruf.getText();

        mahasiswaDAO.simpanNilai(nim, tugas, kuis, mid, semester, rata, huruf);
    }
    
    private void updateNilaiHuruf() {
    // Mengambil nilai rata-rata dari input field
    double rata = Double.parseDouble(jTextrata.getText());

    // Mengonversi nilai rata-rata ke huruf
    String huruf;
    if (rata >= 85) {
        huruf = "A";
    } else if (rata >= 70) {
        huruf = "B";
    } else if (rata >= 60) {
        huruf = "C";
    } else {
        huruf = "D";
    }

    // Menampilkan nilai huruf di input field jTexthuruf
    jTexthuruf.setText(huruf);
}

private void updateNilaiRata() {
    // Mengambil nilai huruf dari input field
    String huruf = jTexthuruf.getText();

    // Mengonversi nilai huruf ke nilai rata-rata
    double rata;
    switch (huruf) {
        case "A":
            rata = 90;
            break;
        case "B":
            rata = 80;
            break;
        case "C":
            rata = 70;
            break;
        default:
            rata = 60;
    }

    // Menampilkan nilai rata-rata di input field jTextrata
    jTextrata.setText(String.valueOf(rata));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTexttugas = new javax.swing.JTextField();
        jTextkuis = new javax.swing.JTextField();
        jTextmid = new javax.swing.JTextField();
        jTextsemester = new javax.swing.JTextField();
        jTextrata = new javax.swing.JTextField();
        jTexthuruf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextnim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nilai Tugas:");

        jLabel2.setText("Nilai Kuis:");

        jLabel3.setText("Nilai Semester:");

        jLabel4.setText("Nilai MID:");

        jLabel5.setText("Nilai Rata-Rata:");

        jLabel6.setText("Huruf Nilai:");

        jButton1.setText("hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextmidActionPerformed(evt);
            }
        });

        jTextrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextrataActionPerformed(evt);
            }
        });

        jTexthuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexthurufActionPerformed(evt);
            }
        });

        jLabel7.setText("NIM:");

        jTextnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnimActionPerformed(evt);
            }
        });

        jLabel8.setText("Menghitung Nilai Mahasiswa");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextmid)
                            .addComponent(jTextsemester)
                            .addComponent(jTextrata)
                            .addComponent(jTexthuruf)
                            .addComponent(jTextkuis)
                            .addComponent(jTexttugas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextnim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTexttugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextkuis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTexthuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    hitungNilai();
    
    String nim = jTextnim.getText();    
    String tugas = jTexttugas.getText();
    String kuis = jTextkuis.getText();
    String mid = jTextmid.getText();
    String semester = jTextsemester.getText();
    String rata = jTextrata.getText();
    String huruf = jTexthuruf.getText();
    
    
    
    mahasiswaDAO.simpanNilai(nim,tugas, kuis, mid, semester, rata, huruf);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextmidActionPerformed

    private void jTexthurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexthurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexthurufActionPerformed

    private void jTextrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextrataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextrataActionPerformed

    private void jTextnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnimActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTexthuruf;
    private javax.swing.JTextField jTextkuis;
    private javax.swing.JTextField jTextmid;
    private javax.swing.JTextField jTextnim;
    private javax.swing.JTextField jTextrata;
    private javax.swing.JTextField jTextsemester;
    private javax.swing.JTextField jTexttugas;
    // End of variables declaration//GEN-END:variables
}
